<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Client;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = [
            [
                'client_code' => 'CLI1001',
                'company_name' => 'Ceylon Tea Company',
                'contact_person_name' => 'Priyanka Wickramasinghe',
                'contact_person_designation' => 'Marketing Manager',
                'email' => 'priyanka.wickramasinghe@ceylontea.lk',
                'phone_number' => '011-2345678',
                'mobile_number' => '077-1234567',
                'address' => '123 Galle Road, Colombo 03',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00300',
                'country' => 'Sri Lanka',
                'website' => 'https://www.ceylontea.lk',
                'industry' => 'Agriculture',
                'client_type' => 'company',
                'status' => 'active',
                'notes' => 'Premium tea export company with international presence.',
            ],
            [
                'client_code' => 'CLI1002',
                'company_name' => 'Lanka Hospitals',
                'contact_person_name' => 'Dr. Nimal Perera',
                'contact_person_designation' => 'Director of Operations',
                'email' => 'nimal.perera@lankahospitals.lk',
                'phone_number' => '011-5432100',
                'mobile_number' => '071-9876543',
                'address' => '456 Independence Avenue, Colombo 07',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'website' => 'https://www.lankahospitals.lk',
                'industry' => 'Healthcare',
                'client_type' => 'company',
                'status' => 'active',
                'notes' => 'Leading private healthcare provider in Sri Lanka.',
            ],
            [
                'client_code' => 'CLI1003',
                'company_name' => 'Dialog Axiata',
                'contact_person_name' => 'Kavinda Silva',
                'contact_person_designation' => 'Brand Manager',
                'email' => 'kavinda.silva@dialog.lk',
                'phone_number' => '011-4567890',
                'mobile_number' => '076-5432109',
                'address' => '789 Bauddhaloka Mawatha, Colombo 07',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'website' => 'https://www.dialog.lk',
                'industry' => 'Telecommunications',
                'client_type' => 'company',
                'status' => 'active',
                'notes' => 'Leading telecommunications service provider.',
            ],
            [
                'client_code' => 'CLI1004',
                'company_name' => 'John Keells Holdings',
                'contact_person_name' => 'Sanduni Fernando',
                'contact_person_designation' => 'Events Coordinator',
                'email' => 'sanduni.fernando@keells.com',
                'phone_number' => '011-7890123',
                'mobile_number' => '075-6789012',
                'address' => '321 Union Place, Colombo 02',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00200',
                'country' => 'Sri Lanka',
                'website' => 'https://www.keells.com',
                'industry' => 'Conglomerate',
                'client_type' => 'company',
                'status' => 'active',
                'notes' => 'Diversified conglomerate with interests in retail, leisure, and transportation.',
            ],
            [
                'client_code' => 'CLI1005',
                'company_name' => 'Sri Lanka Tourism Promotion Bureau',
                'contact_person_name' => 'Rukshan Mendis',
                'contact_person_designation' => 'Deputy Director',
                'email' => 'rukshan.mendis@sltpb.gov.lk',
                'phone_number' => '011-2345679',
                'mobile_number' => '077-2345678',
                'address' => '80 Galle Road, Colombo 03',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00300',
                'country' => 'Sri Lanka',
                'website' => 'https://www.srilanka.travel',
                'industry' => 'Tourism',
                'client_type' => 'government',
                'status' => 'active',
                'notes' => 'Government agency responsible for promoting Sri Lanka tourism.',
            ],
            [
                'client_code' => 'CLI1006',
                'company_name' => 'MAS Holdings',
                'contact_person_name' => 'Tharindu Rajapaksa',
                'contact_person_designation' => 'Marketing Executive',
                'email' => 'tharindu.rajapaksa@masholdings.com',
                'phone_number' => '011-3456789',
                'mobile_number' => '071-3456789',
                'address' => '123 Horton Place, Colombo 07',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'website' => 'https://www.masholdings.com',
                'industry' => 'Manufacturing',
                'client_type' => 'company',
                'status' => 'active',
                'notes' => 'Leading apparel manufacturer and exporter.',
            ],
            [
                'client_code' => 'CLI1007',
                'company_name' => 'World Vision Sri Lanka',
                'contact_person_name' => 'Anushka Jayawardena',
                'contact_person_designation' => 'Program Manager',
                'email' => 'anushka.jayawardena@worldvision.lk',
                'phone_number' => '011-4567891',
                'mobile_number' => '076-4567890',
                'address' => '456 Kynsey Road, Colombo 08',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00800',
                'country' => 'Sri Lanka',
                'website' => 'https://www.worldvision.lk',
                'industry' => 'NGO',
                'client_type' => 'ngo',
                'status' => 'active',
                'notes' => 'International humanitarian organization focused on child welfare.',
            ],
            [
                'client_code' => 'CLI1008',
                'company_name' => 'Cargills Ceylon',
                'contact_person_name' => 'Dilani Gunasekara',
                'contact_person_designation' => 'Retail Manager',
                'email' => 'dilani.gunasekara@cargillsceylon.com',
                'phone_number' => '011-5678901',
                'mobile_number' => '075-5678901',
                'address' => '789 Duplication Road, Colombo 03',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00300',
                'country' => 'Sri Lanka',
                'website' => 'https://www.cargillsceylon.com',
                'industry' => 'Retail',
                'client_type' => 'company',
                'status' => 'active',
                'notes' => 'Leading retail chain with supermarkets and food courts.',
            ],
            [
                'client_code' => 'CLI1009',
                'company_name' => 'Hatton National Bank',
                'contact_person_name' => 'Chaminda Bandara',
                'contact_person_designation' => 'Branch Manager',
                'email' => 'chaminda.bandara@hnb.lk',
                'phone_number' => '011-6789012',
                'mobile_number' => '077-6789012',
                'address' => '321 HNB Towers, Colombo 02',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00200',
                'country' => 'Sri Lanka',
                'website' => 'https://www.hnb.lk',
                'industry' => 'Banking',
                'client_type' => 'company',
                'status' => 'active',
                'notes' => 'Premier private sector commercial bank.',
            ],
            [
                'client_code' => 'CLI1010',
                'company_name' => 'Sri Lankan Airlines',
                'contact_person_name' => 'Nishadi Karunaratne',
                'contact_person_designation' => 'Customer Relations Manager',
                'email' => 'nishadi.karunaratne@srilankan.com',
                'phone_number' => '011-7890124',
                'mobile_number' => '071-7890123',
                'address' => '456 Airline Centre, Colombo 02',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00200',
                'country' => 'Sri Lanka',
                'website' => 'https://www.srilankan.com',
                'industry' => 'Aviation',
                'client_type' => 'company',
                'status' => 'active',
                'notes' => 'National flag carrier airline of Sri Lanka.',
            ],
        ];

        foreach ($clients as $client) {
            Client::create($client);
        }
    }
}
